version: '3'

services:
    nginx:
        image: nginx:stable-alpine
        restart: 'always'
        ports:
            - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
            - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
        volumes:
            - ./www:/var/www/html
            - ./config/vhosts/:/etc/nginx/sites-enabled
            - ./logs/nginx:/var/log/nginx

    php:
        build: ./bin/${PHP_VERSION}
        restart: 'always'
        volumes:
            - ./www:/var/www/html
            - ./logs/tmp:/tmp
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "127.0.0.1:9000:9000"
        links:
            - database
            - nginx
        environment:
            XDEBUG_CONFIG: "remote_host=${XDEBUG_LOCAL_IP} remote_enable=1"
            PHP_IDE_CONFIG: "serverName=${XDEBUG_SERVER_NAME}"
            PMA_PORT: ${HOST_MACHINE_PMA_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    database:
        build: ./bin/${DB_VERSION}
        restart: 'always'
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        ports:
            - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        volumes: 
            - /sessions
            - ./config/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
        links:
            - database
        ports:
            - "${HOST_MACHINE_PMA_PORT}:80"
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
